apiVersion: v1
kind: Service
metadata:
  name: f-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: pos-frontend
  ports:
  - protocol: TCP
    port: 8080         # Port ของ Service
    targetPort: 3000   # Port ของ Pod
    name: http
